### ISSUE TITLE
How to prevent text being converted to path?

### ISSUE THREAD

**Issue by ooxi** [skagedal/svgclip#1]
I want to use svgclip to remove the whitespace around a couple of images containing text. This works quite well, however the text automatically gets converted to paths and now sometimes overflows.

How can I prevent text from being converted to paths when using svgclip?

**Comment by skagedal** [comment]
I unfortunately don't know the answer to that! Maybe someone at Inkscape does.

**Comment by ooxi** [comment]
Thanks for coming back to the question anyway :-)
