### ISSUE TITLE
New approach after inkscape 1.0 !

### ISSUE THREAD

**Issue by RainYang-RY** [skagedal/svgclip#8]
`inkscape --export-type=svg -o --export-area-drawing  .\test.svg`

without gui.

**Comment by skagedal** [comment]
Nice! I included this in the README

**Comment by umlaeute** [comment]
With inkscape-1.2.1 (as packaged in Debian/sid), this will resave the file as `--export-area-drawing.svg`, without actually changing it.

the proper invocation is

```sh
inkscape --export-type=svg -o test_cropped.svg --export-area-drawing ./test.svg
```

**Comment by skagedal** [comment]
Thank you @umlaeute, that sounds reasonable. Updated README.
